import { useEffect, useState } from "react";
import { checkMcpHealth, getCapabilities, getWorkspaces, setCapabilityEnabled } from "./api";
import type { CapabilityState, MCPRecord, SkillRecord } from "./types";

export function CapabilitiesStudio() {
  const [workspaces, setWorkspaces] = useState<Array<{ id: string; name: string; path: string }>>([]);
  const [workspaceId, setWorkspaceId] = useState<string | undefined>();
  const [state, setState] = useState<CapabilityState | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  async function refresh(id = workspaceId) {
    try { const value = await getCapabilities(id); setState(value); if (value.workspace) setWorkspaceId(value.workspace.id); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load capabilities"); }
  }
  useEffect(() => { void getWorkspaces().then((items) => { setWorkspaces(items); if (items[0]) void refresh(items[0].id); }).catch(() => setError("Unable to load workspaces")); }, []);
  async function toggle(type: "skills" | "mcp", item: SkillRecord | MCPRecord) {
    setBusy(item.id); setError(null);
    try { await setCapabilityEnabled(type, item.id, !item.enabled, item.updated_at); await refresh(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Capability changed in another tab"); }
    finally { setBusy(null); }
  }
  async function health(item: MCPRecord) { setBusy(item.id); try { await checkMcpHealth(item.id); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Health check failed"); } finally { setBusy(null); } }
  return <div className="page fade-in"><div className="page-heading"><div><div className="eyebrow">GOVERNANCE</div><h1>Capabilities</h1><p className="muted">What GravityClaw can use in each deliberately narrow worker.</p></div><select className="workspace-select" value={workspaceId ?? ""} onChange={(e) => { setWorkspaceId(e.target.value); void refresh(e.target.value); }}>{workspaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{error && <div className="inline-error studio-error">{error}</div>}{state && <><section className="capability-hero panel"><div><div className="eyebrow">EXECUTION BOUNDARY</div><h2>{state.workspace?.name ?? "Workspace"}</h2><p>AGY receives broad freedom only inside this worker boundary.</p></div><span className="state-pill healthy">Container enforced</span></section><div className="capability-grid"><section className="panel capability-panel"><div className="panel-header"><h2>Skills</h2><span className="mono">{state.skills.length} visible</span></div>{state.skills.map((item) => <CapabilityRow key={item.id} name={item.name} detail={`${item.scope} · ${item.validation_state.toLowerCase()} · ${item.version}`} enabled={item.enabled} busy={busy === item.id} onToggle={() => void toggle("skills", item)} />)}{state.skills.length === 0 && <div className="empty-source">No skills are registered for this workspace.</div>}</section><section className="panel capability-panel"><div className="panel-header"><h2>MCP servers</h2><span className="mono">{state.mcp.length} visible</span></div>{state.mcp.map((item) => <McpRow key={item.id} item={item} busy={busy === item.id} onToggle={() => void toggle("mcp", item)} onHealth={() => void health(item)} />)}{state.mcp.length === 0 && <div className="empty-source">No MCP servers are registered for this workspace.</div>}</section></div><div className="capability-lower"><section className="panel isolation-panel"><div className="panel-header"><h2>Isolation</h2><span className="state-pill healthy">Protected</span></div>{Object.entries(state.isolation).map(([key, value]) => <Fact key={key} label={key.replaceAll("_", " ")} value={value} />)}<div className="secret-note">⌁ Secret values are injected only at worker construction. This view exposes references and counts, never values.</div></section><section className="panel snapshot-panel"><div className="panel-header"><h2>Run snapshots</h2><span className="mono">immutable</span></div>{state.snapshots.slice(0, 8).map((snapshot) => <div className="snapshot-row" key={snapshot.run_id}><div><strong>Run {snapshot.run_id.slice(0, 8)}</strong><span>{snapshot.profile} · {formatDate(snapshot.created_at)}</span></div><code>{snapshot.manifest_hash.slice(0, 10)}…</code></div>)}{state.snapshots.length === 0 && <div className="empty-source">No run capability snapshots yet.</div>}</section></div></>}</div>;
}

function CapabilityRow({ name, detail, enabled, busy, onToggle }: { name: string; detail: string; enabled: boolean; busy: boolean; onToggle: () => void }) { return <div className="capability-row"><span className={`capability-icon ${enabled ? "on" : "off"}`}>{enabled ? "✓" : "○"}</span><div><strong>{name}</strong><span>{detail}</span></div><button className={`capability-toggle ${enabled ? "on" : ""}`} disabled={busy} onClick={onToggle}>{busy ? "…" : enabled ? "Enabled" : "Disabled"}</button></div>; }
function McpRow({ item, busy, onToggle, onHealth }: { item: MCPRecord; busy: boolean; onToggle: () => void; onHealth: () => void }) { return <div className="capability-row"><span className={`health-glyph ${item.health_state.toLowerCase()}`}>●</span><div><strong>{item.name}</strong><span>{item.transport} · {item.health_state.toLowerCase()} · {item.last_checked_at ? formatDate(item.last_checked_at) : "not checked"}</span>{Object.keys(item.env_refs).length > 0 && <small className="secret-ref">{Object.values(item.env_refs).join(" · ")}</small>}</div><div className="capability-actions"><button className="icon-button" title="Check health" disabled={busy} onClick={onHealth}>↻</button><button className={`capability-toggle ${item.enabled ? "on" : ""}`} disabled={busy} onClick={onToggle}>{busy ? "…" : item.enabled ? "Enabled" : "Disabled"}</button></div></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="detail-row"><span>{label}</span><strong>{value}</strong></div>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
