import { useEffect, useState } from "react";
import { getRunContextManifest, getRuns, previewContext } from "./api";
import type { ContextManifest, RunRecord } from "./types";

export function ContextStudio() {
  const [runs, setRuns] = useState<RunRecord[]>([]); const [selected, setSelected] = useState<RunRecord | null>(null); const [manifest, setManifest] = useState<ContextManifest | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; void getRuns().then((items) => { if (!cancelled) { setRuns(items); if (items[0]) setSelected(items[0]); } }).catch((reason) => !cancelled && setError(messageOf(reason, "Unable to load runs"))); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!selected) return; let cancelled = false; void getRunContextManifest(selected.id).then((item) => !cancelled && setManifest(item)).catch((reason) => !cancelled && setError(messageOf(reason, "Context manifest unavailable"))); return () => { cancelled = true; }; }, [selected?.id]);
  const sources = manifest?.sources ?? []; const used = sources.filter((item) => item.included); const excluded = sources.filter((item) => !item.included); const usedTokens = manifest?.estimated_tokens ?? used.reduce((sum, item) => sum + item.estimated_tokens, 0); const budget = manifest?.budget_tokens ?? 0; const percent = budget ? Math.min(100, Math.round((usedTokens / budget) * 100)) : 0;
  return <div className="page fade-in context-studio"><div className="page-heading"><div><div className="eyebrow">M5 CONTEXT PROTOCOL</div><h1>Context Inspector</h1><p className="muted">What GravityClaw knew for one run — immutable and inspectable.</p></div><span className="studio-health"><span className="status-dot green" /> read-only manifests</span></div>{error && <div className="inline-error studio-error">{error}</div>}<div className="context-layout"><aside className="context-runs panel"><div className="panel-header"><h2>Runs</h2><span className="muted-text">{runs.length}</span></div>{runs.map((run) => <button key={run.id} className={selected?.id === run.id ? "selected" : ""} onClick={() => setSelected(run)}><span className={`status-dot ${run.status === "completed" ? "green" : run.status === "running" ? "blue" : "amber"}`} /><div><strong>{String(run.request.prompt ?? "Untitled run").slice(0, 48)}</strong><small>{run.request.context_profile ?? "chat"} · {run.id.slice(0, 8)}</small></div></button>)}{runs.length === 0 && <Empty title="No runs" detail="Context manifests appear after dispatch." />}</aside><main className="context-detail panel">{selected && manifest ? <><div className="context-detail-head"><div><div className="eyebrow">RUN {selected.id.slice(0, 12)}</div><h2>{String(selected.request.prompt ?? "Untitled run")}</h2><span className="editor-meta">Profile {manifest.profile ?? "chat"} · {manifest.lifecycle ?? "sealed"} · fingerprint {String(manifest.context_fingerprint ?? "—").slice(0, 12)}</span></div><span className="immutable-badge">IMMUTABLE</span></div><section className="context-meter"><div><strong>{usedTokens.toLocaleString()}</strong><span> / {(budget || 0).toLocaleString()} estimated tokens</span><b>{percent}%</b></div><div className="meter-track"><span style={{ width: `${percent}%` }} /></div></section><div className="context-summary-grid"><Metric label="Included sources" value={String(used.length)} /><Metric label="Excluded sources" value={String(excluded.length)} /><Metric label="Characters" value={String(manifest.characters ?? "—")} /><Metric label="Identity hash" value={String(manifest.identity_fingerprint ?? "—").slice(0, 10)} /></div><SourceGroup title="Included context" sources={used} /><SourceGroup title="Excluded by policy" sources={excluded} excluded /></> : <Empty title="Select a run" detail="Choose a persisted run to inspect its sealed context." />}</main></div><ContextPreview /></div>;
}

function ContextPreview() { const [task, setTask] = useState(""); const [profile, setProfile] = useState("coding"); const [result, setResult] = useState<ContextManifest | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); async function compile() { if (!task.trim()) return; setBusy(true); setError(null); try { setResult((await previewContext(task, profile)).manifest); } catch (reason) { setError(messageOf(reason, "Preview failed")); } finally { setBusy(false); } } return <section className="preview-panel panel"><div><div className="eyebrow">NO EXECUTION</div><h2>Simulate context</h2><p className="muted">Compile a bounded preview without creating a job, launching AGY, or mutating memory.</p></div><div className="preview-form"><select className="text-input" value={profile} onChange={(event) => setProfile(event.target.value)}><option value="chat">Chat profile</option><option value="coding">Coding profile</option><option value="heartbeat">Heartbeat profile</option><option value="scheduled">Scheduled profile</option></select><textarea className="text-input preview-task" value={task} onChange={(event) => setTask(event.target.value)} placeholder="Investigate the scheduler restart bug…" rows={2} /><button className="primary-button" disabled={busy || !task.trim()} onClick={() => void compile()}>{busy ? "Compiling…" : "Compile preview"}</button></div>{error && <div className="inline-error">{error}</div>}{result && <div className="preview-result"><div className="context-meter"><strong>{result.estimated_tokens?.toLocaleString()} tokens</strong><span> · {result.sources?.filter((item) => item.included).length ?? 0} included sources</span></div><div className="source-chips">{(result.sources ?? []).map((source) => <span className={source.included ? "included" : "excluded"} key={source.label}>{source.included ? "✓" : "×"} {source.label}</span>)}</div></div>}</section>; }
function SourceGroup({ title, sources, excluded = false }: { title: string; sources: ContextManifest["sources"]; excluded?: boolean }) { return <section className="source-group"><div className="section-label">{title}</div>{sources?.length ? sources.map((source) => <article className={`source-row ${excluded ? "excluded" : ""}`} key={source.label}><span>{excluded ? "×" : "✓"}</span><div><strong>{source.label}</strong><small>{source.category} · {source.trust} · {source.estimated_tokens} tokens</small>{excluded && <em>{source.exclusion_reason ?? "excluded by policy"}</em>}</div><code>{source.sha256?.slice(0, 10) ?? "—"}</code></article>) : <div className="muted empty-source">None</div>}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="context-metric"><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="studio-empty"><span>◎</span><strong>{title}</strong><small>{detail}</small></div>; }
function messageOf(reason: unknown, fallback: string): string { return reason instanceof Error ? reason.message : fallback; }
